[tool.poetry]
name = "yark-api"
version = "0.1.0"
description = "Official REST API for Yark archive management"
authors = ["Owen Griffiths <root@ogriffiths.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "yark_api" }]

[tool.poetry.dependencies]
python = "~3.11"
click = "^8.1.3"
aiohttp = "^3.8.3"

[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
poethepoet = "^0.18.1"
types-colorama = "^0.4.15.4"
types-requests = "^2.28.11.8"
black = "^22.12.0"
pylint = "^2.16.1"

[tool.poe.tasks]
lint = { shell = "set -e && mypy yark --strict && pylint yark" }
fmt = "black yark"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
