[package]
name = "yark-archive"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
